
export const ADD_ARTICLE_REQUESTED = 'ADD_ARTICLE_REQUESTED';
export const ADD_ARTICLE_REJECTED = 'ADD_ARTICLE_REJECTED';
export const ADD_ARTICLE_FULFILLED = 'ADD_ARTICLE_FULFILLED';

export type ADD_ARTICLE_REQUESTED = typeof ADD_ARTICLE_REQUESTED;
export type ADD_ARTICLE_REJECTED = typeof ADD_ARTICLE_REJECTED;
export type ADD_ARTICLE_FULFILLED = typeof ADD_ARTICLE_FULFILLED;

export const DELETE_ARTICLE_REQUESTED = 'DELETE_ARTICLE_REQUESTED';
export const DELETE_ARTICLE_REJECTED = 'DELETE_ARTICLE_REJECTED';
export const DELETE_ARTICLE_FULFILLED = 'DELETE_ARTICLE_FULFILLED';

export type DELETE_ARTICLE_REQUESTED = typeof DELETE_ARTICLE_REQUESTED;
export type DELETE_ARTICLE_REJECTED = typeof DELETE_ARTICLE_REJECTED;
export type DELETE_ARTICLE_FULFILLED = typeof DELETE_ARTICLE_FULFILLED;

export const TOGGLE_ARTICLE_READ_REQUESTED = 'TOGGLE_ARTICLE_READ_REQUESTED';
export const TOGGLE_ARTICLE_READ_REJECTED = 'TOGGLE_ARTICLE_READ_REJECTED';
export const TOGGLE_ARTICLE_READ_FULFILLED = 'TOGGLE_ARTICLE_READ_FULFILLED';

export type TOGGLE_ARTICLE_READ_REQUESTED = typeof TOGGLE_ARTICLE_READ_REQUESTED;
export type TOGGLE_ARTICLE_READ_REJECTED = typeof TOGGLE_ARTICLE_READ_REJECTED;
export type TOGGLE_ARTICLE_READ_FULFILLED = typeof TOGGLE_ARTICLE_READ_FULFILLED;

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export type SET_VISIBILITY_FILTER = typeof SET_VISIBILITY_FILTER;

export const SET_PROJECT_FILTER = 'SET_PROJECT_FILTER';
export type SET_PROJECT_FILTER = typeof SET_PROJECT_FILTER;

export const ADD_ARTICLE_TO_PROJECT_REQUESTED = 'ADD_ARTICLE_TO_PROJECT_REQUESTED';
export type ADD_ARTICLE_TO_PROJECT_REQUESTED = typeof ADD_ARTICLE_TO_PROJECT_REQUESTED;

export const ADD_ARTICLE_TO_PROJECT_FULFILLED =
    'ADD_ARTICLE_TO_PROJECT_FULFILLED';
export type ADD_ARTICLE_TO_PROJECT_FULFILLED = typeof ADD_ARTICLE_TO_PROJECT_FULFILLED;

export const ADD_ARTICLE_TO_PROJECT_REJECTED = 'ADD_ARTICLE_TO_PROJECT_REJECTED';
export type ADD_ARTICLE_TO_PROJECT_REJECTED = typeof ADD_ARTICLE_TO_PROJECT_REJECTED;

export const SORT_ARTICLES = 'SORT_ARTICLES'
export type SORT_ARTICLES = typeof SORT_ARTICLES;